[package]
name = "advent-2019"
version = "0.1.0"
authors = ["marcopiraccini <marco.piraccini@converge.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "0.1.0"
aoc-runner-derive = "0.1.0"
